name: Deploy Lambda Function

on: 
  push:
    branches:
      - main
# pull_request:
#   branches:
#     - main
# schedule:
#   - cron: 0 12 * * 1

jobs:
  build: 
    runs-on: ubuntu-latest
#   runs-on: ${{ matrix.os }}
#   strategy:
#     matrix:
#       python-version: [3.x, 4.x, 5.x, 6.x]
#       os: [ubuntu-latest, windows-latest, macOS-latest] 
#   environment:
#     name: Development
#     url: 
#   outputs:
#     script-file: ${{ steps.publish.outputs.script-file }}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
#         python-version: ${{ matrix.python-version }}
#     - name: Cache dependencies
#       uses: actions/cache@v2
#       with:
#         path:
#         key:
      - name: Install libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
            cd function
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with: 
          name: zipped-bundle
          path: ${{ github.sha }}.zip
#       - name: publish filename
#         id: publish
#         run: find <path> -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
    
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: zipped-bundle
      - name: Configure AWs credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha }}.zip s3://my-bucket-ihdbvdjhvb/${{ github.sha }}.zip
      
  deploy: 
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Configure AWs credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update function code
        run: |
            aws lambda update-function-code \
            --function-name my-function \
            --s3-bucket my-bucket-ihdbvdjhvb \
            --s3-key ${{ github.sha }}.zip \
            --publish

#deploy: 
#   runs-on: ubuntu-latest
#   needs: upload
#   steps:
#     - name: Build & Push Docker Image
#       run: docker build . -t <repo/image> 
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#       run: docker push <repo/image>
# OR
#       uses: mr-smithers-excellent/docker-build-push@v5
#       with:
#         image: repo/image
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
